apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - rbac.yaml
  - manifest.yaml
patches:
  - patch: |
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1managed-by"
        value: Flux
      - op: remove
        path: "/metadata/labels/helm.sh~1chart"
    target:
      kind: (Deployment|Service)
