---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/gimlet-io/capacitor
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  interval: 1m
  path: "./self-host/yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: capacitor-next
  targetNamespace: flux-system
configMapGenerator:
  - name: capacitor-next
    literals:
      - OIDC_ISSUER=https://login.microsoftonline.com/{tenant_id}/v2.0
      - OIDC_CLIENT_ID=capacitor-next
      - OIDC_REDIRECT_URL=https://capacitor-next.example.com/auth/callback
